services:
  Qwen3.5-35B-A3B:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: Qwen3.5-35B-A3B
    ports:
      - "8788:8788"
    volumes:
      - ./models:/models
    environment:
      LLAMA_ARG_MODEL: /models/unsloth/Qwen3.5-35B-A3B-GGUF/Q8_K_XL/Qwen3.5-35B-A3B-UD-Q8_K_XL.gguf
      LLAMA_ARG_N_GPU_LAYERS: 99
      LLAMA_ARG_N_PARALLEL: 4
      LLAMA_ARG_FLASH_ATTN: 1
      LLAMA_ARG_JINJA: 1
      LLAMA_ARG_SEED: 3407
      LLAMA_ARG_TEMP: 1.0
      LLAMA_ARG_TOP_P: 0.95
      LLAMA_ARG_TOP_K: 20
      LLAMA_ARG_MIN_P: 0.0
      LLAMA_ARG_PRESENCE_PENALTY: 1.5
      LLAMA_ARG_CTX_SIZE: 262144
      LLAMA_ARG_CACHE_TYPE_K: q8_0
      LLAMA_ARG_CACHE_TYPE_V: q8_0
      LLAMA_ARG_HOST: 0.0.0.0
      LLAMA_ARG_PORT: 8788
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
