services:
  GLM-4.7-Flash-UD-Q4_K_XL:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: GLM-4.7-Flash-UD-Q4_K_XL
    ports:
      - "8788:8788"
    volumes:
      - ./models:/models
    environment:
      LLAMA_ARG_MODEL: /models/unsloth/GLM-4.7-Flash-UD-Q4_K_XL/GLM-4.7-Flash-UD-Q4_K_XL.gguf
      LLAMA_ARG_N_PARALLEL: 1
      LLAMA_ARG_FLASH_ATTN: 1
      LLAMA_ARG_JINJA: 1
      LLAMA_ARG_TEMP: 1.0
      LLAMA_ARG_TOP_P: 0.95
      LLAMA_ARG_MIN_P: 0.01
      LLAMA_ARG_REPEAT_PENALTY: 1.0
      LLAMA_ARG_HOST: 0.0.0.0
      LLAMA_ARG_PORT: 8788
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
